library(quanteda)
library(factoextra)
library(FactoMineR)
library(quanteda.textmodels)
library(quanteda.textplots)
library(quanteda.textstats)
library(stopwords)
library(stringr) # per usare la funzione str_replace_all()
library(tm)
library(lsa)
library(tidyr)
library(dplyr)
library(udpipe)
library(Matrix)
data("stopwords_en")
stopwords_en



colnames(CSV_reddit)[colnames(CSV_reddit) == "Post Text"] <- "text"
CSV_reddit = CSV_reddit %>%
  drop_na(text)


# write.csv(CSV_reddit, "CSV_reddit_gd.csv")



CSV_reddit$text=str_replace_all(CSV_reddit$text,"#[a-z,A-Z]*","")
CSV_reddit$text=str_replace_all(CSV_reddit$text,"@[a-z,A-Z]*","")
CSV_reddit$text=str_replace_all(CSV_reddit$text,"_[a-z,A-Z]*","")
CSV_reddit$text=str_replace_all(CSV_reddit$text,'[^[:ascii:]àèéìòùáíóú]',"")
CSV_reddit$text=str_replace_all(CSV_reddit$text,'\\w*[0-9]+\\w*\\s*',"")
CSV_reddit$text=tolower(CSV_reddit$text)




# the corpus function is used to create a corpus object from a collection of text documents. 
# A corpus is a structured set of texts (called "documents") that can be analyzed using various 
# statistical and machine learning techniques.

corpus=corpus(CSV_reddit$text, docnames=CSV_reddit$ID,
              docvars=as.data.frame(CSV_reddit$Date))


token=tokens(corpus, what = "word", remove_punct = TRUE, remove_symbols = TRUE,
             remove_numbers = TRUE, remove_url = TRUE, remove_separators = TRUE,
             split_hyphens = T, include_docvars = TRUE, padding = FALSE)
dfm=dfm(token) #matrice termini per documenti
top=textstat_frequency(dfm)
write.csv(top, "legge_zipf.csv")
n_token = sum(ntoken(token))
n_type = 8154
n_apax = 3633
lexext= n_type/n_token
freqmean = n_token/n_type
ricerc=nrow(subset(top,frequency == 1))/n_type

CSV_reddit$text=gsub(pattern = "'",replacement =  " ", CSV_reddit$text)
CSV_reddit$text=gsub(pattern = "'",replacement =  " ", CSV_reddit$text)
CSV_reddit$text=gsub(pattern = "'",replacement =  " ", CSV_reddit$text)
CSV_reddit$text=gsub(pattern = "binairy",replacement =  "binary", CSV_reddit$text)
CSV_reddit$text=gsub(pattern = "nonbinairy",replacement =  "nonbinary", CSV_reddit$text)
CSV_reddit$text=gsub(pattern = "non binary",replacement =  "nonbinary", CSV_reddit$text)
CSV_reddit$text=gsub(pattern = "non-binary",replacement =  "nonbinary", CSV_reddit$text)
CSV_reddit$text=gsub(pattern = " nb ",replacement =  " nonbinary ", CSV_reddit$text)
CSV_reddit$text=gsub(pattern = "aren",replacement =  " are not ", CSV_reddit$text)
CSV_reddit$text=gsub(pattern = "arent",replacement =  " are not ", CSV_reddit$text)
CSV_reddit$text=gsub(pattern = " gd ",replacement =  " gender dysphoria ", CSV_reddit$text)
CSV_reddit$text=gsub(pattern = "GD",replacement =  " gender dysphoria ", CSV_reddit$text)
CSV_reddit$text=gsub(pattern = "cross dress",replacement =  "crossdress", CSV_reddit$text)
CSV_reddit$text=gsub(pattern = "dead name",replacement =  " deadname ", CSV_reddit$text)
token <- tokens_select(token, pattern = stopwords_en, selection = 'remove')
token <- tokens_select(token, pattern = stopwords('en'), selection = 'remove')
#token <- tokens_select(token, pattern = "na", selection = 'remove')
token <- tokens_select(token, pattern = mystop, selection = 'remove')
token <- tokens_select(token, pattern = adverbs_to_remove, selection = 'remove')
#token = tokens_wordstem(token)
token = lemmatize(token)

token_bi=tokens_ngrams(token, n = 1:2, skip = 0L, concatenator = "_")

---------------------------------- Document X Feature Matrix --------------------------------
dfm=dfm(token) #matrice termini per documenti
top=textstat_frequency(dfm)
dfm_trim=dfm_trim(dfm,min_termfreq = 15, min_docfreq = 10)
top_trim=textstat_frequency(dfm_trim)

dfm_bi=dfm(token_bi)
top_bi=textstat_frequency(dfm_bi)

# Convert dfm_norm_mat to dfm


#tm = convert(dfm_trim, to = "tm")

dfm_tfidf(dfm)

dtm_clean_tfidf <- dtm_remove_tfidf(dfm, top = 100)

dfm=as.dfm(dtm_clean_tfidf)

dfm2 = textstat_frequency(dfm2)


CA.res=textmodel_ca(dfm_trim, nd = 5, sparse = T)
CA.res_bi=textmodel_ca(dfm_bi, nd = 5, sparse = T)

profilo_medio_reason = data.frame()

fviz_ca_col(CA.res, repel = T, axes = c(1, 2), pointsize = "cos2", labelsize =5, select.col = list(contrib = 80),  col.col = "contrib",
            gradient.cols = c( "blue", "orange", "red"))  + 
  ggplot2::theme(panel.background = element_rect(fill = '#8AB7DE'),
                 plot.background= element_rect(fill= "#FFD2CC"),
                 legend.title = element_text(size = 20, face="bold"),
                 legend.text = element_text(size = 20, face="bold")) +
  labs(title = "") +
  theme(plot.title = element_text(size = 20, face="bold"),
        axis.title.x = element_text(size=20, face="bold", color = "black"),
        axis.title.y = element_text(size=20, face="bold", color = "black")) 

fviz_ca_biplot(CA.res, repel = T, select.col = list(contrib = 80))

textplot_wordcloud(dfm, comparison = F,
                   min_count = 1, adjust=F,min_size = 0.5, max_size = 10, max_words = 100, color = "#8AB7DE")

sparsity(exp_dfm)

eig.val <- get_eigenvalue(CA.res)
res.col <- get_ca_col(CA.res)
res.col$coord          # Coordinates
res.col$contrib        # Contributions to the PCs
res.col$cos2 
cos_acl = data.frame(res.col$cos2)
write.csv(cos_acl, "cos_acl.csv")

contrib = data.frame(res.col$contrib)
write.csv(contrib, "contrib_acl.csv")


col.contrib=CA.res$col$contrib# contributi assoluti delle colonne
col.cos2=CA.res$col$cos2#contributi relativi delle colonne

fviz_eig(CA.res, addlabels = TRUE, ylim = c(0, 80))+ 
  ggplot2::theme(panel.background = element_rect(fill ="#FFD2CC"),
                 plot.background= element_rect(fill= '#8AB7DE')) + labs(title = "")
  

options(ggrepel.max.overlaps=60)

words<-c("nonbinary","amab","afab","hrt","binder","therapy","deadname", "pmdd", 
         "trans", "misgendering", "identity", "transgender", "crossdress", "ftm", "mtf",
         "tomboy")



---------------------------- PROVA DEI SUBSET PER SINGOLE PAROLE --------------------------------
# 
  
  subset = CSV_reddit%>%
  filter(str_detect(text,"hrt")|
           str_detect(text,"nonbin")|
           str_detect(text,"amab")|
           str_detect(text,"afab")|
           str_detect(text,"bind")|
           str_detect(text,"therap")|
           str_detect(text,"deadnam")|
           str_detect(text,"pmdd")|
           str_detect(text,"misgend")|
           str_detect(text,"identi")|
           str_detect(text,"crossdress")|
           str_detect(text,"ftm")|
           str_detect(text,"mtf")|
           str_detect(text,"tomboy")|
           str_detect(text,"beard")|
           str_detect(text,"ass")|
           str_detect(text,"thighs")|
           str_detect(text,"vagin")|
           str_detect(text,"dick")|
           str_detect(text,"genital")|
           str_detect(text,"bottom")|
           str_detect(text,"hips")|
           str_detect(text,"boob")|
           str_detect(text,"top")|
           str_detect(text,"penis")|
           str_detect(text,"breast")|
           str_detect(text,"chest"))


body_words = c("beard", "ass", "thighs", "vagin", "dick" , "genital", "bottom",
               "hips", "boob", "top","penis", "breast", "chest")


--------------------------------------------------------------------------------------------------------------------------------------------------
  
mystop = c("lately", "hey", "possibly", "wouldnt", "re", "day", "past", "ago", "bit", "post", "else", "else", "week",
             "specifically", "incredibly", "whats",  "bc", "mainly", "due", "shes", "time", "maybe", "theres", "lol", 
             "alot", "stand", "night", "answer", "youre", "months", "ts", "social", "recent", "word", "late", "theyre",
             "whether", "minutes", "suddenly", "forever", "sub", "reality", "typically", "anybody", "idk", "thats", "anymore",
             "email", "project", "survey", "link", "study", "team", "information", "university", "us", "ask", "certain",
             "similar", "begin", "writing", "morning", "title", "edit", "speak", "folks", "anyways", "country", "actual", 
             "amount", "topic", "saw", "month", "absolutely", "asked", "asking", "can", "cant", "couldn", "couldnt", "currently", 
             "d", "didn", "didnt", "doesn", "doesnt", "don", "dont", "hi", "t", "m", "im", "ve", "s", "ive", "isn", "isnt", "na" , 
             "yo", "whats","havent", "haven", "lot", "intermittently", "gender", "dysphoria", "want", "etc", "stuff", "ll", 
             "dunno","research", "excercise", "allow", "main", "sit", "yea", "bulk", "laura", "buy", "gonna", "entire", "wouldn", "wont", "wasnt", "wasn",
           "exercise", "thanks", "insurance", "pre", "base")

mystop= data.frame(mystop)
mystop %>%
  arrange(mystop)

ly = top %>%
  filter(str_detect(feature, "ly")) %>%
  arrange(desc(frequency))
c = data.frame(unique(ly$feature))
c = c %>%
  filter(unique.ly.feature.!= "family" &
           unique.ly.feature.!= "girly"&
           unique.ly.feature.!= "ugly"&
           unique.ly.feature.!= "sexually"&
           unique.ly.feature.!= "bully"&
           unique.ly.feature.!= "belly"&
           unique.ly.feature.!= "holy"&
           unique.ly.feature.!= "curly"&
           unique.ly.feature.!= "analysis"&
           unique.ly.feature.!= "fly"&
           unique.ly.feature.!= "electrolysis"&
           unique.ly.feature.!= "therapeutically"&
           unique.ly.feature.!= "polyamorous"&
           unique.ly.feature.!= "supply"&
           unique.ly.feature.!= "analyzer"&
           unique.ly.feature.!= "flying"&
           unique.ly.feature.!= "psychoanalyst"&
           unique.ly.feature.!= "analyze"&
           unique.ly.feature.!= "catalyst")

adverbs_to_remove = c$unique.ly.feature.

lemmatize <- function(token) {
  token<-tokens_replace(token,pattern="abused",replacement="abuse")
  token<-tokens_replace(token,pattern="abuses",replacement="abuse")
  token<-tokens_replace(token,pattern="abusing",replacement="abuse")
  token<-tokens_replace(token,pattern="acceptance",replacement="accept")
  token<-tokens_replace(token,pattern="acceptation",replacement="accept")
  token<-tokens_replace(token,pattern="accepts",replacement="accept")
  token<-tokens_replace(token,pattern="accounts",replacement="account")
  token<-tokens_replace(token,pattern="acted",replacement="act")
  token<-tokens_replace(token,pattern="acting",replacement="act")
  token<-tokens_replace(token,pattern="addressed",replacement="address")
  token<-tokens_replace(token,pattern="addresses",replacement="address")
  token<-tokens_replace(token,pattern="addressing",replacement="address")
  token<-tokens_replace(token,pattern="adults",replacement="adult")
  token<-tokens_replace(token,pattern="advances",replacement="advance")
  token<-tokens_replace(token,pattern="affected",replacement="affect")
  token<-tokens_replace(token,pattern="affecting",replacement="affect")
  token<-tokens_replace(token,pattern="affects",replacement="affect")
  token<-tokens_replace(token,pattern="ages",replacement="age")
  token<-tokens_replace(token,pattern="agreed",replacement="agree")
  token<-tokens_replace(token,pattern="agreeing",replacement="agree")
  token<-tokens_replace(token,pattern="allowed",replacement="allow")
  token<-tokens_replace(token,pattern="allowing",replacement="allow")
  token<-tokens_replace(token,pattern="allows",replacement="allow")
  token<-tokens_replace(token,pattern="amabs",replacement="amab")
  token<-tokens_replace(token,pattern="androgenous",replacement="androgynous")
  token<-tokens_replace(token,pattern="androgyny",replacement="androgynous")
  token<-tokens_replace(token,pattern="androgynously",replacement="androgynous")
  
  
  token<-tokens_replace(token,pattern="annoyed",replacement="annoying")
  token<-tokens_replace(token,pattern="appearing",replacement="appear")
  token<-tokens_replace(token,pattern="appears",replacement="appear")
  token<-tokens_replace(token,pattern="appearances",replacement="appearance")
  token<-tokens_replace(token,pattern="appointments",replacement="appointment")
  token<-tokens_replace(token,pattern="areas",replacement="area")
  token<-tokens_replace(token,pattern="aspects",replacement="aspect")
  token<-tokens_replace(token,pattern="associated",replacement="associate")
  token<-tokens_replace(token,pattern="assumed",replacement="assume")
  token<-tokens_replace(token,pattern="assumes",replacement="assume")
  token<-tokens_replace(token,pattern="assuming",replacement="assume")
  token<-tokens_replace(token,pattern="attacked",replacement="attack")
  token<-tokens_replace(token,pattern="attacking",replacement="attack")
  token<-tokens_replace(token,pattern="attacks",replacement="attack")
  token<-tokens_replace(token,pattern="attracting",replacement="attract")
  token<-tokens_replace(token,pattern="attracted",replacement="attract")
  token<-tokens_replace(token,pattern="avoided",replacement="avoid")
  token<-tokens_replace(token,pattern="avoiding",replacement="avoid")
  token<-tokens_replace(token,pattern="aweful",replacement="awful")
  token<-tokens_replace(token,pattern="accepting",replacement="accept")
  token<-tokens_replace(token,pattern="accepted",replacement="accept")
  token<-tokens_replace(token,pattern="anxious",replacement="anxiety")
  token<-tokens_replace(token,pattern="appreciated",replacement="appreciate")
  token<-tokens_replace(token,pattern="agend",replacement="agender")
  
  token<-tokens_replace(token,pattern="based",replacement="base")
  token<-tokens_replace(token,pattern="basis",replacement="base")
  token<-tokens_replace(token,pattern="becomes",replacement="become")
  token<-tokens_replace(token,pattern="becoming",replacement="become")
  token<-tokens_replace(token,pattern="began",replacement="begin")
  token<-tokens_replace(token,pattern="begins",replacement="begin")
  token<-tokens_replace(token,pattern="beginning",replacement="begin")
  token<-tokens_replace(token,pattern="begins",replacement="begin")
  token<-tokens_replace(token,pattern="begun",replacement="begin")
  token<-tokens_replace(token,pattern="believed",replacement="believe")
  token<-tokens_replace(token,pattern="believes",replacement="believe")
  token<-tokens_replace(token,pattern="believing",replacement="believe")
  token<-tokens_replace(token,pattern="belongs",replacement="belong")
  token<-tokens_replace(token,pattern="belonging",replacement="belong")
  token<-tokens_replace(token,pattern="belonged",replacement="belong")
  token<-tokens_replace(token,pattern="binding",replacement="binder")
  token<-tokens_replace(token,pattern="binders",replacement="binder")
  token<-tokens_replace(token,pattern="bind",replacement="binder")
  token<-tokens_replace(token,pattern="binded",replacement="binder")
  token<-tokens_replace(token,pattern="boob",replacement="boobs")
  token<-tokens_replace(token,pattern="bothered",replacement="bother")
  token<-tokens_replace(token,pattern="bothering",replacement="bother")
  token<-tokens_replace(token,pattern="bothers",replacement="bother")
  token<-tokens_replace(token,pattern="bringing",replacement="bring")
  token<-tokens_replace(token,pattern="brings",replacement="bring")
  token<-tokens_replace(token,pattern="breaks",replacement="break")
  token<-tokens_replace(token,pattern="broke",replacement="break")
  token<-tokens_replace(token,pattern="broken",replacement="break")
  token<-tokens_replace(token,pattern="brothers",replacement="brother")
  token<-tokens_replace(token,pattern="bullied",replacement="bully")
  token<-tokens_replace(token,pattern="bullying",replacement="bully")
  token<-tokens_replace(token,pattern="buying",replacement="buy")
  token<-tokens_replace(token,pattern="bought",replacement="buy")
  token<-tokens_replace(token,pattern="buys",replacement="buy")
  token<-tokens_replace(token,pattern="became",replacement="become")
  token<-tokens_replace(token,pattern="bi",replacement="bisexual")
  token<-tokens_replace(token,pattern="bodies",replacement="body")
  token<-tokens_replace(token,pattern="boys",replacement="boy")
  token<-tokens_replace(token,pattern="breasts",replacement="breast")
  token<-tokens_replace(token,pattern="brought",replacement="bring")
  token<-tokens_replace(token,pattern="bras",replacement="bra")
  token<-tokens_replace(token,pattern="badly",replacement="bad")
  token<-tokens_replace(token,pattern="born",replacement="birth")
  
  
  token<-tokens_replace(token,pattern="hrt",replacement="hurt")
  
  token<-tokens_replace(token,pattern="calls",replacement="call")
  token<-tokens_replace(token,pattern="cared",replacement="care")
  token<-tokens_replace(token,pattern="cares",replacement="care")
  token<-tokens_replace(token,pattern="caring",replacement="care")
  token<-tokens_replace(token,pattern="cases",replacement="case")
  token<-tokens_replace(token,pattern="causes",replacement="cause")
  token<-tokens_replace(token,pattern="causing",replacement="cause")
  token<-tokens_replace(token,pattern="chances",replacement="chance")
  token<-tokens_replace(token,pattern="changed",replacement="change")
  token<-tokens_replace(token,pattern="characters",replacement="character")
  token<-tokens_replace(token,pattern="checked",replacement="check")
  token<-tokens_replace(token,pattern="checks",replacement="check")
  token<-tokens_replace(token,pattern="checking",replacement="check")
  token<-tokens_replace(token,pattern="children",replacement="child")
  token<-tokens_replace(token,pattern="chooses",replacement="choose")
  token<-tokens_replace(token,pattern="choosing",replacement="choose")
  token<-tokens_replace(token,pattern="chose",replacement="choose")
  token<-tokens_replace(token,pattern="chosen",replacement="choose")
  token<-tokens_replace(token,pattern="cisgender",replacement="cis")
  token<-tokens_replace(token,pattern="closed",replacement="close")
  token<-tokens_replace(token,pattern="closing",replacement="close")
  token<-tokens_replace(token,pattern="comforted",replacement="comfort")
  token<-tokens_replace(token,pattern="comforting",replacement="comfort")
  token<-tokens_replace(token,pattern="comforts",replacement="comfort")
  token<-tokens_replace(token,pattern="comments",replacement="comment")
  token<-tokens_replace(token,pattern="commented",replacement="comment")
  token<-tokens_replace(token,pattern="commenting",replacement="comment")
  token<-tokens_replace(token,pattern="communities",replacement="community")
  token<-tokens_replace(token,pattern="completed",replacement="complete")
  token<-tokens_replace(token,pattern="completing",replacement="complete")
  token<-tokens_replace(token,pattern="concerned",replacement="concern")
  token<-tokens_replace(token,pattern="concerning",replacement="concern")
  token<-tokens_replace(token,pattern="concerns",replacement="concern")
  token<-tokens_replace(token,pattern="conservatives",replacement="conservative")
  token<-tokens_replace(token,pattern="continued",replacement="continue")
  token<-tokens_replace(token,pattern="continues",replacement="continue")
  token<-tokens_replace(token,pattern="conversations",replacement="conversation")
  token<-tokens_replace(token,pattern="convinced",replacement="convince")
  token<-tokens_replace(token,pattern="convincing",replacement="convince")
  token<-tokens_replace(token,pattern="copes",replacement="cope")
  token<-tokens_replace(token,pattern="coping",replacement="cope")
  token<-tokens_replace(token,pattern="corrected",replacement="correct")
  token<-tokens_replace(token,pattern="correcting",replacement="correct")
  token<-tokens_replace(token,pattern="continued",replacement="care")
  token<-tokens_replace(token,pattern="cried",replacement="cry")
  token<-tokens_replace(token,pattern="crossed",replacement="cross")
  token<-tokens_replace(token,pattern="crossdresses",replacement="crossdress")
  token<-tokens_replace(token,pattern="crossdressering",replacement="crossdress")
  token<-tokens_replace(token,pattern="crossdresser",replacement="crossdress")
  token<-tokens_replace(token,pattern="crossdressed",replacement="crossdress")
  token<-tokens_replace(token,pattern="crossdressing",replacement="crossdress")
  token<-tokens_replace(token,pattern="crushed",replacement="crush")
  token<-tokens_replace(token,pattern="crushes",replacement="crush")
  token<-tokens_replace(token,pattern="crushing",replacement="crush")
  token<-tokens_replace(token,pattern="cutting",replacement="cut")
  token<-tokens_replace(token,pattern="cycles",replacement="cycle")
  token<-tokens_replace(token,pattern="called",replacement="call")
  token<-tokens_replace(token,pattern="calling",replacement="call")
  token<-tokens_replace(token,pattern="changes",replacement="happen")
  token<-tokens_replace(token,pattern="changing",replacement="happen")
  token<-tokens_replace(token,pattern="changend",replacement="happen")
  token<-tokens_replace(token,pattern="clothes",replacement="clothing")
  token<-tokens_replace(token,pattern="considered",replacement="consider")
  token<-tokens_replace(token,pattern="considering",replacement="consider")
  token<-tokens_replace(token,pattern="crying",replacement="cry")
  token<-tokens_replace(token,pattern="caused",replacement="cause")
  token<-tokens_replace(token,pattern="comfortable",replacement="comfort")
  token<-tokens_replace(token,pattern="coming",replacement="come")
  token<-tokens_replace(token,pattern="comes",replacement="come")
  token<-tokens_replace(token,pattern="confused",replacement="confusion")
  token<-tokens_replace(token,pattern="confusing",replacement="confusion")
  token<-tokens_replace(token,pattern="dads",replacement="father")
  token<-tokens_replace(token,pattern="daughters",replacement="daughter")
  token<-tokens_replace(token,pattern="dad",replacement="father")
  token<-tokens_replace(token,pattern="days",replacement="day")
  token<-tokens_replace(token,pattern="depressed",replacement="depression")
  token<-tokens_replace(token,pattern="diagnosed",replacement="diagnose")
  token<-tokens_replace(token,pattern="dressed",replacement="dress")
  token<-tokens_replace(token,pattern="dresses",replacement="dress")
  token<-tokens_replace(token,pattern="dressing",replacement="dress")
  token<-tokens_replace(token,pattern="doctors",replacement="doctor")
  token<-tokens_replace(token,pattern="dealing",replacement="deal")
  token<-tokens_replace(token,pattern="damned",replacement="damn")
  token<-tokens_replace(token,pattern="deadnamed",replacement="deadname")
  token<-tokens_replace(token,pattern="deadnames",replacement="deadname")
  token<-tokens_replace(token,pattern="deadnaming",replacement="deadname")
  token<-tokens_replace(token,pattern="deals",replacement="deal")
  token<-tokens_replace(token,pattern="dealt",replacement="deal")
  token<-tokens_replace(token,pattern="decided",replacement="decide")
  token<-tokens_replace(token,pattern="decides",replacement="decide")
  token<-tokens_replace(token,pattern="deepen",replacement="deep")
  token<-tokens_replace(token,pattern="deepened",replacement="deep")
  token<-tokens_replace(token,pattern="deepening",replacement="deep")
  token<-tokens_replace(token,pattern="deeper",replacement="deep")
  token<-tokens_replace(token,pattern="deepest",replacement="deep")
  token<-tokens_replace(token,pattern="deeply",replacement="deep")
  token<-tokens_replace(token,pattern="depth",replacement="denial")
  token<-tokens_replace(token,pattern="denied",replacement="denial")
  token<-tokens_replace(token,pattern="denies",replacement="denial")
  token<-tokens_replace(token,pattern="denying",replacement="denial")
  token<-tokens_replace(token,pattern="deny",replacement="denial")
  token<-tokens_replace(token,pattern="depressing",replacement="depression")
  token<-tokens_replace(token,pattern="depressive",replacement="depression")
  token<-tokens_replace(token,pattern="described",replacement="description")
  token<-tokens_replace(token,pattern="describe",replacement="descriptions")
  token<-tokens_replace(token,pattern="describes",replacement="descriptions")
  token<-tokens_replace(token,pattern="desirable",replacement="desire")
  token<-tokens_replace(token,pattern="desired",replacement="desire")
  token<-tokens_replace(token,pattern="desires",replacement="desire")
  token<-tokens_replace(token,pattern="details",replacement="detail")
  token<-tokens_replace(token,pattern="detailing",replacement="detail")
  token<-tokens_replace(token,pattern="detailed",replacement="detail")
  token<-tokens_replace(token,pattern="develop",replacement="development")
  token<-tokens_replace(token,pattern="developed",replacement="development")
  token<-tokens_replace(token,pattern="developing",replacement="development")
  token<-tokens_replace(token,pattern="diagnose",replacement="diagnosis")
  token<-tokens_replace(token,pattern="diagnostic",replacement="diagnosis")
  token<-tokens_replace(token,pattern="dicks",replacement="dick")
  token<-tokens_replace(token,pattern="died",replacement="die")
  token<-tokens_replace(token,pattern="differ",replacement="difference")
  token<-tokens_replace(token,pattern="differences",replacement="difference")
  token<-tokens_replace(token,pattern="different",replacement="difference")
  token<-tokens_replace(token,pattern="differential",replacement="difference")
  token<-tokens_replace(token,pattern="differently",replacement="difference")
  token<-tokens_replace(token,pattern="differnce",replacement="difference")
  token<-tokens_replace(token,pattern="differs",replacement="difference")
  token<-tokens_replace(token,pattern="difficulties",replacement="difficult")
  token<-tokens_replace(token,pattern="difficulty",replacement="difficult")
  token<-tokens_replace(token,pattern="disconnect",replacement="disconnection")
  token<-tokens_replace(token,pattern="disconnected",replacement="disconnection")
  token<-tokens_replace(token,pattern="disconnecting",replacement="disconnection")
  token<-tokens_replace(token,pattern="discover",replacement="discovery")
  token<-tokens_replace(token,pattern="discovered",replacement="discovery")
  token<-tokens_replace(token,pattern="discovering",replacement="discovery")
  token<-tokens_replace(token,pattern="discuss",replacement="discussion")
  token<-tokens_replace(token,pattern="discussed",replacement="discussion")
  token<-tokens_replace(token,pattern="discussing",replacement="discussion")
  token<-tokens_replace(token,pattern="disgusts",replacement="disgust")
  token<-tokens_replace(token,pattern="disgusted",replacement="disgust")
  token<-tokens_replace(token,pattern="disgusting",replacement="disgust")
  token<-tokens_replace(token,pattern="disgustingly",replacement="disgust")
  token<-tokens_replace(token,pattern="disliked",replacement="dislike")
  token<-tokens_replace(token,pattern="disliking",replacement="dislike")
  token<-tokens_replace(token,pattern="disordered",replacement="disorder")
  token<-tokens_replace(token,pattern="disorders",replacement="disorder")
  token<-tokens_replace(token,pattern="disphoria",replacement="dysphoria")
  token<-tokens_replace(token,pattern="distressed",replacement="distress")
  token<-tokens_replace(token,pattern="distresses",replacement="distress")
  token<-tokens_replace(token,pattern="distressing",replacement="distress")
  token<-tokens_replace(token,pattern="doubts",replacement="doubt")
  token<-tokens_replace(token,pattern="doubted",replacement="doubt")
  token<-tokens_replace(token,pattern="drawing",replacement="draw")
  token<-tokens_replace(token,pattern="drawn",replacement="draw")
  token<-tokens_replace(token,pattern="draws",replacement="draw")
  token<-tokens_replace(token,pattern="dreamed",replacement="dream")
  token<-tokens_replace(token,pattern="dreams",replacement="dream")
  token<-tokens_replace(token,pattern="dreaming",replacement="dream")
  token<-tokens_replace(token,pattern="dreamt",replacement="dream")
  token<-tokens_replace(token,pattern="driven",replacement="drive")
  token<-tokens_replace(token,pattern="driver",replacement="drive")
  token<-tokens_replace(token,pattern="drives",replacement="drive")
  token<-tokens_replace(token,pattern="driving",replacement="drive")
  token<-tokens_replace(token,pattern="driving",replacement="drop")
  token<-tokens_replace(token,pattern="dropped",replacement="drop")
  token<-tokens_replace(token,pattern="dropping",replacement="drop")
  token<-tokens_replace(token,pattern="drops",replacement="drop")
  token<-tokens_replace(token,pattern="dudes",replacement="dude")
  token<-tokens_replace(token,pattern="dyphoria",replacement="dysphoria")
  token<-tokens_replace(token,pattern="dyphoric",replacement="dysphoria")
  token<-tokens_replace(token,pattern="dypshoria",replacement="dysphoria")
  token<-tokens_replace(token,pattern="dysforia",replacement="dysphoria")
  token<-tokens_replace(token,pattern="dyshoria",replacement="dysphoria")
  token<-tokens_replace(token,pattern="dyshporia",replacement="dysphoria")
  token<-tokens_replace(token,pattern="dysohoria",replacement="dysphoria")
  token<-tokens_replace(token,pattern="dysohoric",replacement="dysphoria")
  token<-tokens_replace(token,pattern="dysphoriaim",replacement="dysphoria")
  token<-tokens_replace(token,pattern="dysphoriais",replacement="dysphoria")
  token<-tokens_replace(token,pattern="dysphoriathen",replacement="dysphoria")
  token<-tokens_replace(token,pattern="dysphoric",replacement="dysphoria")
  
  token<-tokens_replace(token,pattern="earlier",replacement="early")
  token<-tokens_replace(token,pattern="earliest",replacement="early")
  token<-tokens_replace(token,pattern="ease",replacement="easy")
  token<-tokens_replace(token,pattern="easily",replacement="easy")
  token<-tokens_replace(token,pattern="eating",replacement="eat")
  token<-tokens_replace(token,pattern="eats",replacement="eat")
  token<-tokens_replace(token,pattern="elses",replacement="else")
  token<-tokens_replace(token,pattern="comforting",replacement="embarassment")
  token<-tokens_replace(token,pattern="embarassed",replacement="embarassment")
  token<-tokens_replace(token,pattern="embarrassed",replacement="embarassment")
  token<-tokens_replace(token,pattern="embarassing",replacement="embarassment")
  token<-tokens_replace(token,pattern="comforting",replacement="embrace")
  token<-tokens_replace(token,pattern="embraced",replacement="embrace")
  token<-tokens_replace(token,pattern="embracing",replacement="embrace")
  token<-tokens_replace(token,pattern="ended",replacement="end")
  token<-tokens_replace(token,pattern="ending",replacement="end")
  token<-tokens_replace(token,pattern="enjoyment",replacement="enjoy")
  token<-tokens_replace(token,pattern="enjoying",replacement="enjoy")
  token<-tokens_replace(token,pattern="enjoys",replacement="enjoy")
  token<-tokens_replace(token,pattern="entirely",replacement="entire")
  token<-tokens_replace(token,pattern="envying",replacement="envy")
  token<-tokens_replace(token,pattern="episodes",replacement="episode")
  token<-tokens_replace(token,pattern="euphoric",replacement="euphoria")
  token<-tokens_replace(token,pattern="exactly",replacement="exact")
  token<-tokens_replace(token,pattern="examples",replacement="example")
  token<-tokens_replace(token,pattern="excited",replacement="excitement")
  token<-tokens_replace(token,pattern="excites",replacement="excitement")
  token<-tokens_replace(token,pattern="exciting",replacement="excitement")
  token<-tokens_replace(token,pattern="exercises",replacement="exercise")
  token<-tokens_replace(token,pattern="exist",replacement="existence")
  token<-tokens_replace(token,pattern="existed",replacement="existence")
  token<-tokens_replace(token,pattern="existential",replacement="existence")
  token<-tokens_replace(token,pattern="existing",replacement="existence")
  token<-tokens_replace(token,pattern="exists",replacement="existence")
  token<-tokens_replace(token,pattern="expect",replacement="expectations")
  token<-tokens_replace(token,pattern="expected",replacement="expectations")
  token<-tokens_replace(token,pattern="expecting",replacement="expectations")
  token<-tokens_replace(token,pattern="expects",replacement="expectations")
  token<-tokens_replace(token,pattern="experimentation",replacement="experiment")
  token<-tokens_replace(token,pattern="experimented",replacement="experiment")
  token<-tokens_replace(token,pattern="experimenting",replacement="experiment")
  token<-tokens_replace(token,pattern="explored",replacement="explore")
  token<-tokens_replace(token,pattern="exploring",replacement="explore")
  token<-tokens_replace(token,pattern="extremely",replacement="extreme")
  token<-tokens_replace(token,pattern="extended",replacement="extentions")
  token<-tokens_replace(token,pattern="extends",replacement="extentions")
  token<-tokens_replace(token,pattern="extensive",replacement="extentions")
  token<-tokens_replace(token,pattern="extensively",replacement="extentions")
  token<-tokens_replace(token,pattern="extend",replacement="extentions")
  token<-tokens_replace(token,pattern="extensions",replacement="extentions")
  token<-tokens_replace(token,pattern="easier",replacement="easy")
  token<-tokens_replace(token,pattern="enjoyed",replacement="enjoy")
  token<-tokens_replace(token,pattern="experiencing",replacement="experience")
  token<-tokens_replace(token,pattern="experienced",replacement="experience")
  token<-tokens_replace(token,pattern="experiences",replacement="experience")
  token<-tokens_replace(token,pattern="emotions",replacement="emotion")
  token<-tokens_replace(token,pattern="envious",replacement="envy")
  
  token<-tokens_replace(token,pattern="facts",replacement="fact")
  token<-tokens_replace(token,pattern="faking",replacement="fake")
  token<-tokens_replace(token,pattern="fallback",replacement="fall")
  token<-tokens_replace(token,pattern="falling",replacement="fall")
  token<-tokens_replace(token,pattern="fallen",replacement="fall")
  token<-tokens_replace(token,pattern="fallout",replacement="fall")
  token<-tokens_replace(token,pattern="falls",replacement="fall")
  token<-tokens_replace(token,pattern="families",replacement="family")
  token<-tokens_replace(token,pattern="familiar",replacement="family")
  token<-tokens_replace(token,pattern="fathers",replacement="father")
  token<-tokens_replace(token,pattern="feared",replacement="fear")
  token<-tokens_replace(token,pattern="fearful",replacement="fear")
  token<-tokens_replace(token,pattern="fearing",replacement="fear")
  token<-tokens_replace(token,pattern="fears",replacement="fear")
  token<-tokens_replace(token,pattern="feature",replacement="features")
  token<-tokens_replace(token,pattern="featured",replacement="features")
  token<-tokens_replace(token,pattern="feelings",replacement="feeling")
  token<-tokens_replace(token,pattern="feels",replacement="feel")
  token<-tokens_replace(token,pattern="feelt",replacement="feel")
  token<-tokens_replace(token,pattern="femal",replacement="female")
  token<-tokens_replace(token,pattern="females",replacement="female")
  token<-tokens_replace(token,pattern="femme",replacement="female")
  token<-tokens_replace(token,pattern="femal",replacement="female")
  token<-tokens_replace(token,pattern="fetishes",replacement="fetish")
  token<-tokens_replace(token,pattern="figured",replacement="figure")
  token<-tokens_replace(token,pattern="findings",replacement="find")
  token<-tokens_replace(token,pattern="finds",replacement="find")
  token<-tokens_replace(token,pattern="fits",replacement="fit")
  token<-tokens_replace(token,pattern="fitted",replacement="fit")
  token<-tokens_replace(token,pattern="flatten",replacement="flat")
  token<-tokens_replace(token,pattern="focused",replacement="focus")
  token<-tokens_replace(token,pattern="focuses",replacement="focus")
  token<-tokens_replace(token,pattern="focusing",replacement="focus")
  token<-tokens_replace(token,pattern="followed",replacement="follow")
  token<-tokens_replace(token,pattern="followers",replacement="follow")
  token<-tokens_replace(token,pattern="following",replacement="follow")
  token<-tokens_replace(token,pattern="follows",replacement="follow")
  token<-tokens_replace(token,pattern="forced",replacement="force")
  token<-tokens_replace(token,pattern="forcing",replacement="force")
  token<-tokens_replace(token,pattern="forms",replacement="form")
  token<-tokens_replace(token,pattern="found",replacement="find")
  token<-tokens_replace(token,pattern="freedom",replacement="free")
  token<-tokens_replace(token,pattern="friend",replacement="friends")
  token<-tokens_replace(token,pattern="friendship",replacement="friends")
  token<-tokens_replace(token,pattern="friendships",replacement="friends")
  token<-tokens_replace(token,pattern="fucked",replacement="fuck")
  token<-tokens_replace(token,pattern="fully",replacement="full")
  token<-tokens_replace(token,pattern="fem",replacement="feminine")
  
  token<-tokens_replace(token,pattern="giving",replacement="give")
  token<-tokens_replace(token,pattern="games",replacement="game")
  token<-tokens_replace(token,pattern="genitalia",replacement="genitals")
  token<-tokens_replace(token,pattern="gaining",replacement="gain")
  token<-tokens_replace(token,pattern="gained",replacement="gain")
  token<-tokens_replace(token,pattern="genders",replacement="gender")
  token<-tokens_replace(token,pattern="generalized",replacement="general")
  token<-tokens_replace(token,pattern="generally",replacement="general")
  token<-tokens_replace(token,pattern="gets",replacement="get")
  token<-tokens_replace(token,pattern="getting",replacement="get")
  token<-tokens_replace(token,pattern="girls",replacement="girl")
  token<-tokens_replace(token,pattern="girlfriends",replacement="girlfriend")
  token<-tokens_replace(token,pattern="given",replacement="give")
  token<-tokens_replace(token,pattern="gives",replacement="give")
  token<-tokens_replace(token,pattern="goes",replacement="go")
  token<-tokens_replace(token,pattern="going",replacement="go")
  token<-tokens_replace(token,pattern="gotten",replacement="got")
  token<-tokens_replace(token,pattern="grades",replacement="grade")
  token<-tokens_replace(token,pattern="grandmother",replacement="grandma")
  token<-tokens_replace(token,pattern="grateful",replacement="gratitude")
  token<-tokens_replace(token,pattern="grately",replacement="great")
  token<-tokens_replace(token,pattern="grew",replacement="growth")
  token<-tokens_replace(token,pattern="grow",replacement="growth")
  token<-tokens_replace(token,pattern="growing",replacement="growth")
  token<-tokens_replace(token,pattern="grown",replacement="growth")
  token<-tokens_replace(token,pattern="guilty",replacement="guilt")
  token<-tokens_replace(token,pattern="guys",replacement="guy")
  
  token<-tokens_replace(token,pattern="happened",replacement="happen")
  token<-tokens_replace(token,pattern="happens",replacement="happen")
  token<-tokens_replace(token,pattern="happening",replacement="happen")
  token<-tokens_replace(token,pattern="helps",replacement="help")
  token<-tokens_replace(token,pattern="helped",replacement="help")
  token<-tokens_replace(token,pattern="hormones",replacement="hormone")
  token<-tokens_replace(token,pattern="harder",replacement="hard")
  token<-tokens_replace(token,pattern="haircut",replacement="hair")
  token<-tokens_replace(token,pattern="haircuts",replacement="hair")
  token<-tokens_replace(token,pattern="hands",replacement="hand")
  token<-tokens_replace(token,pattern="happier",replacement="happy")
  token<-tokens_replace(token,pattern="happiest",replacement="happy")
  token<-tokens_replace(token,pattern="harmed",replacement="harm")
  token<-tokens_replace(token,pattern="harming",replacement="harm")
  token<-tokens_replace(token,pattern="hates",replacement="hate")
  token<-tokens_replace(token,pattern="hated",replacement="hate")
  token<-tokens_replace(token,pattern="hating",replacement="hate")
  token<-tokens_replace(token,pattern="hatring",replacement="hate")
  token<-tokens_replace(token,pattern="healthcare",replacement="healt")
  token<-tokens_replace(token,pattern="heard",replacement="hear")
  token<-tokens_replace(token,pattern="hearing",replacement="hear")
  token<-tokens_replace(token,pattern="helpful",replacement="help")
  token<-tokens_replace(token,pattern="helping",replacement="help")
  token<-tokens_replace(token,pattern="hiding",replacement="hide")
  token<-tokens_replace(token,pattern="hittings",replacement="hit")
  token<-tokens_replace(token,pattern="hits",replacement="hit")
  token<-tokens_replace(token,pattern="holdings",replacement="hold")
  token<-tokens_replace(token,pattern="holds",replacement="hold")
  token<-tokens_replace(token,pattern="hopefully",replacement="hope")
  token<-tokens_replace(token,pattern="hopings",replacement="hope")
  token<-tokens_replace(token,pattern="hormonal",replacement="hormone")
  token<-tokens_replace(token,pattern="humans",replacement="human")
  token<-tokens_replace(token,pattern="hurts",replacement="hurt")
  token<-tokens_replace(token,pattern="hurting",replacement="hurt")
  
  token<-tokens_replace(token,pattern="interested",replacement="interest")
  token<-tokens_replace(token,pattern="identifiable",replacement="identity")
  token<-tokens_replace(token,pattern="identification",replacement="identity")
  token<-tokens_replace(token,pattern="identified",replacement="identity")
  token<-tokens_replace(token,pattern="identifies",replacement="identity")
  token<-tokens_replace(token,pattern="identify",replacement="identity")
  token<-tokens_replace(token,pattern="identifying",replacement="identity")
  token<-tokens_replace(token,pattern="identities",replacement="identity")
  token<-tokens_replace(token,pattern="ignored",replacement="ignore")
  token<-tokens_replace(token,pattern="ignoring",replacement="ignore")
  token<-tokens_replace(token,pattern="images",replacement="image")
  token<-tokens_replace(token,pattern="imaginary",replacement="imagine")
  token<-tokens_replace(token,pattern="imagination",replacement="imagine")
  token<-tokens_replace(token,pattern="imagined",replacement="imagine")
  token<-tokens_replace(token,pattern="imagining",replacement="imagine")
  token<-tokens_replace(token,pattern="included",replacement="include")
  token<-tokens_replace(token,pattern="includes",replacement="include")
  token<-tokens_replace(token,pattern="including",replacement="include")
  token<-tokens_replace(token,pattern="inclusive",replacement="include")
  token<-tokens_replace(token,pattern="insecure",replacement="insecurity")
  token<-tokens_replace(token,pattern="insecurities",replacement="insecurity")
  token<-tokens_replace(token,pattern="interesting",replacement="interest")
  token<-tokens_replace(token,pattern="interestingly",replacement="interest")
  token<-tokens_replace(token,pattern="interests",replacement="interest")
  token<-tokens_replace(token,pattern="issues",replacement="issue")
  
  token<-tokens_replace(token,pattern="jealous",replacement="jealousy")
  token<-tokens_replace(token,pattern="jealously",replacement="jealousy")
  token<-tokens_replace(token,pattern="jobs",replacement="job")
  token<-tokens_replace(token,pattern="joked",replacement="joke")
  token<-tokens_replace(token,pattern="jokes",replacement="joke")
  token<-tokens_replace(token,pattern="joking",replacement="joke")
  token<-tokens_replace(token,pattern="jokingly",replacement="joke")
  token<-tokens_replace(token,pattern="judge",replacement="judgement")
  token<-tokens_replace(token,pattern="judged",replacement="judgement")
  token<-tokens_replace(token,pattern="judging",replacement="judgement")
  token<-tokens_replace(token,pattern="judgment",replacement="judgement")
  
  token<-tokens_replace(token,pattern="keeps",replacement="keep")
  token<-tokens_replace(token,pattern="keeping",replacement="keep")
  token<-tokens_replace(token,pattern="kept",replacement="keep")
  token<-tokens_replace(token,pattern="kids",replacement="kid")
  token<-tokens_replace(token,pattern="knew",replacement="know")
  token<-tokens_replace(token,pattern="knowing",replacement="know")
  token<-tokens_replace(token,pattern="known",replacement="know")
  token<-tokens_replace(token,pattern="knows",replacement="know")
  
  token<-tokens_replace(token,pattern="labeled",replacement="label")
  token<-tokens_replace(token,pattern="labeling",replacement="label")
  token<-tokens_replace(token,pattern="labelled",replacement="label")
  token<-tokens_replace(token,pattern="labelling",replacement="label")
  token<-tokens_replace(token,pattern="labels",replacement="label")
  token<-tokens_replace(token,pattern="lacking",replacement="lack")
  token<-tokens_replace(token,pattern="largely",replacement="large")
  token<-tokens_replace(token,pattern="larger",replacement="large")
  token<-tokens_replace(token,pattern="largest",replacement="large")
  token<-tokens_replace(token,pattern="lasted",replacement="last")
  token<-tokens_replace(token,pattern="lasting",replacement="last")
  token<-tokens_replace(token,pattern="lastly",replacement="last")
  token<-tokens_replace(token,pattern="lasts",replacement="last")
  token<-tokens_replace(token,pattern="later",replacement="late")
  token<-tokens_replace(token,pattern="laugh",replacement="laughter")
  token<-tokens_replace(token,pattern="laughed",replacement="laughter")
  token<-tokens_replace(token,pattern="laughing",replacement="laughter")
  token<-tokens_replace(token,pattern="laughs",replacement="laughter")
  token<-tokens_replace(token,pattern="leading",replacement="lead")
  token<-tokens_replace(token,pattern="leads",replacement="lead")
  token<-tokens_replace(token,pattern="leaner",replacement="lean")
  token<-tokens_replace(token,pattern="leaning",replacement="lean")
  token<-tokens_replace(token,pattern="learned",replacement="learn")
  token<-tokens_replace(token,pattern="learnt",replacement="learn")
  token<-tokens_replace(token,pattern="learning",replacement="learn")
  token<-tokens_replace(token,pattern="leaves",replacement="leave")
  token<-tokens_replace(token,pattern="leaving",replacement="leave")
  token<-tokens_replace(token,pattern="legally",replacement="legal")
  token<-tokens_replace(token,pattern="legs",replacement="leg")
  token<-tokens_replace(token,pattern="lenght",replacement="length")
  token<-tokens_replace(token,pattern="lengths",replacement="length")
  token<-tokens_replace(token,pattern="lengthy",replacement="length")
  token<-tokens_replace(token,pattern="lesbians",replacement="lesbian")
  token<-tokens_replace(token,pattern="lessen",replacement="less")
  token<-tokens_replace(token,pattern="lessens",replacement="less")
  token<-tokens_replace(token,pattern="lets",replacement="let")
  token<-tokens_replace(token,pattern="letting",replacement="let")
  token<-tokens_replace(token,pattern="levels",replacement="level")
  token<-tokens_replace(token,pattern="lgbtia",replacement="lgbt")
  token<-tokens_replace(token,pattern="lgbtq",replacement="lgbt")
  token<-tokens_replace(token,pattern="lgbtqi",replacement="lgbt")
  token<-tokens_replace(token,pattern="lgbtqia",replacement="lgbt")
  token<-tokens_replace(token,pattern="liar",replacement="lie")
  token<-tokens_replace(token,pattern="lied",replacement="lie")
  token<-tokens_replace(token,pattern="lies",replacement="lie")
  token<-tokens_replace(token,pattern="lying",replacement="lie")
  token<-tokens_replace(token,pattern="lines",replacement="line")
  token<-tokens_replace(token,pattern="listened",replacement="listen")
  token<-tokens_replace(token,pattern="longer",replacement="long")
  token<-tokens_replace(token,pattern="longest",replacement="long")
  token<-tokens_replace(token,pattern="looked",replacement="look")
  token<-tokens_replace(token,pattern="looking",replacement="look")
  token<-tokens_replace(token,pattern="looks",replacement="look")
  token<-tokens_replace(token,pattern="losing",replacement="lose")
  token<-tokens_replace(token,pattern="loss",replacement="lose")
  token<-tokens_replace(token,pattern="lost",replacement="lose")
  token<-tokens_replace(token,pattern="lots",replacement="lot")
  token<-tokens_replace(token,pattern="loved",replacement="love")
  token<-tokens_replace(token,pattern="lovely",replacement="love")
  token<-tokens_replace(token,pattern="lovers",replacement="love")
  token<-tokens_replace(token,pattern="loves",replacement="love")
  token<-tokens_replace(token,pattern="loving",replacement="love")
  token<-tokens_replace(token,pattern="lowest",replacement="low")
  token<-tokens_replace(token,pattern="lucky",replacement="luck")
  token<-tokens_replace(token,pattern="luckily",replacement="luck")
  token<-tokens_replace(token,pattern="lived",replacement="live")
  token<-tokens_replace(token,pattern="living",replacement="live")
  
  token<-tokens_replace(token,pattern="made",replacement="make")
  token<-tokens_replace(token,pattern="makes",replacement="make")
  token<-tokens_replace(token,pattern="making",replacement="make")
  token<-tokens_replace(token,pattern="means",replacement="mean")
  token<-tokens_replace(token,pattern="medically",replacement="medical")
  token<-tokens_replace(token,pattern="medicated",replacement="medical")
  token<-tokens_replace(token,pattern="medicine",replacement="medical")
  token<-tokens_replace(token,pattern="medication",replacement="medical")
  token<-tokens_replace(token,pattern="medications",replacement="medical")
  token<-tokens_replace(token,pattern="men",replacement="man")
  token<-tokens_replace(token,pattern="mens",replacement="man")
  token<-tokens_replace(token,pattern="mentally",replacement="mental")
  token<-tokens_replace(token,pattern="mentioned",replacement="mention")
  token<-tokens_replace(token,pattern="mentioning",replacement="mention")
  token<-tokens_replace(token,pattern="mentions",replacement="mention")
  token<-tokens_replace(token,pattern="mirrors",replacement="mirror")
  token<-tokens_replace(token,pattern="misgendered",replacement="misgendering")
  token<-tokens_replace(token,pattern="misgender",replacement="misgendering")
  token<-tokens_replace(token,pattern="misgenders",replacement="misgendering")
  token<-tokens_replace(token,pattern="misidentified",replacement="misgendering")
  token<-tokens_replace(token,pattern="misogynistic",replacement="misogyny")
  token<-tokens_replace(token,pattern="missed",replacement="miss")
  token<-tokens_replace(token,pattern="missing",replacement="miss")
  token<-tokens_replace(token,pattern="mistaken",replacement="mistake")
  token<-tokens_replace(token,pattern="mistakes",replacement="mistake")
  token<-tokens_replace(token,pattern="moms",replacement="mom")
  token<-tokens_replace(token,pattern="mother",replacement="mom")
  token<-tokens_replace(token,pattern="mother",replacement="mom")
  token<-tokens_replace(token,pattern="moments",replacement="moment")
  token<-tokens_replace(token,pattern="moved",replacement="move")
  token<-tokens_replace(token,pattern="meant",replacement="mean")
  token<-tokens_replace(token,pattern="masc",replacement="masculine")
  token<-tokens_replace(token,pattern="mum",replacement="mother")
  
  token<-tokens_replace(token,pattern="natural",replacement="nature")
  token<-tokens_replace(token,pattern="naturally",replacement="nature")
  token<-tokens_replace(token,pattern="nb",replacement="nonbinary")
  token<-tokens_replace(token,pattern="needed",replacement="need")
  token<-tokens_replace(token,pattern="needing",replacement="need")
  token<-tokens_replace(token,pattern="noticeable",replacement="notice")
  token<-tokens_replace(token,pattern="noticed",replacement="notice")
  token<-tokens_replace(token,pattern="notices",replacement="notice")
  token<-tokens_replace(token,pattern="noticing",replacement="notice")
  token<-tokens_replace(token,pattern="needs",replacement="need")
  token<-tokens_replace(token,pattern="nails",replacement="nail")
  token<-tokens_replace(token,pattern="names",replacement="name")
  
  token<-tokens_replace(token,pattern="offence",replacement="offense")
  token<-tokens_replace(token,pattern="offend",replacement="offense")
  token<-tokens_replace(token,pattern="offended",replacement="offense")
  token<-tokens_replace(token,pattern="offending",replacement="offense")
  token<-tokens_replace(token,pattern="offends",replacement="offense")
  token<-tokens_replace(token,pattern="offensive",replacement="offense")
  token<-tokens_replace(token,pattern="offensively",replacement="offense")
  token<-tokens_replace(token,pattern="older",replacement="old")
  token<-tokens_replace(token,pattern="opened",replacement="open")
  token<-tokens_replace(token,pattern="opening",replacement="open")
  token<-tokens_replace(token,pattern="openly",replacement="open")
  token<-tokens_replace(token,pattern="opinions",replacement="opinion")
  token<-tokens_replace(token,pattern="options",replacement="option")
  token<-tokens_replace(token,pattern="ordered",replacement="order")
  token<-tokens_replace(token,pattern="orders",replacement="order")
  
  token<-tokens_replace(token,pattern="panicking",replacement="panic")
  token<-tokens_replace(token,pattern="panicked",replacement="panic")
  token<-tokens_replace(token,pattern="parental",replacement="parent")
  token<-tokens_replace(token,pattern="parents",replacement="parent")
  token<-tokens_replace(token,pattern="partners",replacement="partner")
  token<-tokens_replace(token,pattern="passed",replacement="pass")
  token<-tokens_replace(token,pattern="passing",replacement="pass")
  token<-tokens_replace(token,pattern="payment",replacement="pay")
  token<-tokens_replace(token,pattern="paycheck",replacement="pay")
  token<-tokens_replace(token,pattern="paying",replacement="pay")
  token<-tokens_replace(token,pattern="peoples",replacement="people")
  token<-tokens_replace(token,pattern="perceives",replacement="perceive")
  token<-tokens_replace(token,pattern="perceived",replacement="perceive")
  token<-tokens_replace(token,pattern="perceiving",replacement="perceive")
  token<-tokens_replace(token,pattern="percepitions",replacement="perceive")
  token<-tokens_replace(token,pattern="percepition",replacement="perceive")
  token<-tokens_replace(token,pattern="periods",replacement="period")
  token<-tokens_replace(token,pattern="physically",replacement="physical")
  token<-tokens_replace(token,pattern="places",replacement="place")
  token<-tokens_replace(token,pattern="played",replacement="play")
  token<-tokens_replace(token,pattern="player",replacement="play")
  token<-tokens_replace(token,pattern="playing",replacement="play")
  token<-tokens_replace(token,pattern="plays",replacement="play")
  token<-tokens_replace(token,pattern="possibility",replacement="possible")
  token<-tokens_replace(token,pattern="posted",replacement="post")
  token<-tokens_replace(token,pattern="posting",replacement="post")
  token<-tokens_replace(token,pattern="posts",replacement="post")
  token<-tokens_replace(token,pattern="problems",replacement="problem")
  token<-tokens_replace(token,pattern="professionally",replacement="professional")
  token<-tokens_replace(token,pattern="pronouns",replacement="pronoun")
  token<-tokens_replace(token,pattern="puts",replacement="put")
  token<-tokens_replace(token,pattern="putting",replacement="put")
  token<-tokens_replace(token,pattern="painful",replacement="pain")
  token<-tokens_replace(token,pattern="preferred",replacement="prefer")
  
  token<-tokens_replace(token,pattern="questionable",replacement="question")
  token<-tokens_replace(token,pattern="questioned",replacement="question")
  token<-tokens_replace(token,pattern="questioning",replacement="question")
  token<-tokens_replace(token,pattern="quickly",replacement="quick")
  
  token<-tokens_replace(token,pattern="rambling",replacement="ramble")
  token<-tokens_replace(token,pattern="ran",replacement="run")
  token<-tokens_replace(token,pattern="running",replacement="run")
  token<-tokens_replace(token,pattern="randomly",replacement="random")
  token<-tokens_replace(token,pattern="ranting",replacement="rant")
  token<-tokens_replace(token,pattern="rarely",replacement="rare")
  token<-tokens_replace(token,pattern="reached",replacement="reach")
  token<-tokens_replace(token,pattern="reaching",replacement="reach")
  token<-tokens_replace(token,pattern="reader",replacement="read")
  token<-tokens_replace(token,pattern="reading",replacement="read")
  token<-tokens_replace(token,pattern="realised",replacement="realisation")
  token<-tokens_replace(token,pattern="realise",replacement="realisation")
  token<-tokens_replace(token,pattern="realize",replacement="realisation")
  token<-tokens_replace(token,pattern="realized",replacement="realisation")
  token<-tokens_replace(token,pattern="realizing",replacement="realisation")
  token<-tokens_replace(token,pattern="reasons",replacement="reason")
  token<-tokens_replace(token,pattern="recently",replacement="recent")
  token<-tokens_replace(token,pattern="recognised",replacement="recognise")
  token<-tokens_replace(token,pattern="recognize",replacement="recognise")
  token<-tokens_replace(token,pattern="recognized",replacement="recognise")
  token<-tokens_replace(token,pattern="recognizing",replacement="recognise")
  token<-tokens_replace(token,pattern="refer",replacement="reference")
  token<-tokens_replace(token,pattern="refused",replacement="refuse")
  token<-tokens_replace(token,pattern="refuses",replacement="refuse")
  token<-tokens_replace(token,pattern="refusing",replacement="refuse")
  token<-tokens_replace(token,pattern="regretting",replacement="regret")
  token<-tokens_replace(token,pattern="regularly",replacement="regular")
  token<-tokens_replace(token,pattern="related",replacement="relate")
  token<-tokens_replace(token,pattern="religious",replacement="religion")
  token<-tokens_replace(token,pattern="religiously",replacement="religion")
  token<-tokens_replace(token,pattern="repulsed",replacement="repulse")
  token<-tokens_replace(token,pattern="repulsion",replacement="repulse")
  token<-tokens_replace(token,pattern="repulsive",replacement="repulse")
  token<-tokens_replace(token,pattern="results",replacement="result")
  token<-tokens_replace(token,pattern="resulted",replacement="result")
  token<-tokens_replace(token,pattern="risked",replacement="risk")
  token<-tokens_replace(token,pattern="risking",replacement="risk")
  token<-tokens_replace(token,pattern="risks",replacement="risk")
  token<-tokens_replace(token,pattern="risky",replacement="risk")
  token<-tokens_replace(token,pattern="roughly",replacement="rough")
  
  token<-tokens_replace(token,pattern="sadness",replacement="sad")
  token<-tokens_replace(token,pattern="safely",replacement="safe")
  token<-tokens_replace(token,pattern="safer",replacement="safe")
  token<-tokens_replace(token,pattern="safety",replacement="safe")
  token<-tokens_replace(token,pattern="said",replacement="say")
  token<-tokens_replace(token,pattern="saying",replacement="say")
  token<-tokens_replace(token,pattern="scared",replacement="scare")
  token<-tokens_replace(token,pattern="scares",replacement="scare")
  token<-tokens_replace(token,pattern="scary",replacement="scare")
  token<-tokens_replace(token,pattern="seeing",replacement="see")
  token<-tokens_replace(token,pattern="seeking",replacement="seek")
  token<-tokens_replace(token,pattern="seemed",replacement="seem")
  token<-tokens_replace(token,pattern="seems",replacement="seem")
  token<-tokens_replace(token,pattern="seen",replacement="see")
  token<-tokens_replace(token,pattern="sees",replacement="see")
  token<-tokens_replace(token,pattern="seriously",replacement="serious")
  token<-tokens_replace(token,pattern="sets",replacement="set")
  token<-tokens_replace(token,pattern="setting",replacement="set")
  token<-tokens_replace(token,pattern="settings",replacement="set")
  token<-tokens_replace(token,pattern="shaped",replacement="shape")
  token<-tokens_replace(token,pattern="shaved",replacement="shave")
  token<-tokens_replace(token,pattern="shaving",replacement="shave")
  token<-tokens_replace(token,pattern="shared",replacement="share")
  token<-tokens_replace(token,pattern="sharing",replacement="share")
  token<-tokens_replace(token,pattern="shirts",replacement="shirt")
  token<-tokens_replace(token,pattern="shoulder",replacement="shoulders")
  token<-tokens_replace(token,pattern="showed",replacement="show")
  token<-tokens_replace(token,pattern="showing",replacement="show")
  token<-tokens_replace(token,pattern="shows",replacement="show")
  token<-tokens_replace(token,pattern="simplest",replacement="simple")
  token<-tokens_replace(token,pattern="simply",replacement="simple")
  token<-tokens_replace(token,pattern="sisters",replacement="sister")
  token<-tokens_replace(token,pattern="sitting",replacement="sit")
  token<-tokens_replace(token,pattern="situations",replacement="situation")
  token<-tokens_replace(token,pattern="skirts",replacement="skirt")
  token<-tokens_replace(token,pattern="sleeping",replacement="sleep")
  token<-tokens_replace(token,pattern="smaller",replacement="small")
  token<-tokens_replace(token,pattern="sounded",replacement="sound")
  token<-tokens_replace(token,pattern="sounding",replacement="sound")
  token<-tokens_replace(token,pattern="sounds",replacement="sound")
  token<-tokens_replace(token,pattern="spaces",replacement="space")
  token<-tokens_replace(token,pattern="spending",replacement="spend")
  token<-tokens_replace(token,pattern="spends",replacement="spend")
  token<-tokens_replace(token,pattern="spent",replacement="spend")
  token<-tokens_replace(token,pattern="spoke",replacement="speak")
  token<-tokens_replace(token,pattern="spoken",replacement="speak")
  token<-tokens_replace(token,pattern="standing",replacement="stand")
  token<-tokens_replace(token,pattern="stands",replacement="stand")
  token<-tokens_replace(token,pattern="stared",replacement="stare")
  token<-tokens_replace(token,pattern="stares",replacement="stare")
  token<-tokens_replace(token,pattern="staring",replacement="stare")
  token<-tokens_replace(token,pattern="started",replacement="start")
  token<-tokens_replace(token,pattern="starting",replacement="start")
  token<-tokens_replace(token,pattern="starts",replacement="start")
  token<-tokens_replace(token,pattern="stayed",replacement="stay")
  token<-tokens_replace(token,pattern="staying",replacement="stay")
  token<-tokens_replace(token,pattern="stays",replacement="stay")
  token<-tokens_replace(token,pattern="stereotypes",replacement="stereotype")
  token<-tokens_replace(token,pattern="stereotypical",replacement="stereotype")
  token<-tokens_replace(token,pattern="stereotypically",replacement="stereotype")
  token<-tokens_replace(token,pattern="stereotyping",replacement="stereotype")
  token<-tokens_replace(token,pattern="stopped",replacement="stop")
  token<-tokens_replace(token,pattern="stopping",replacement="stop")
  token<-tokens_replace(token,pattern="stops",replacement="stop")
  token<-tokens_replace(token,pattern="stories",replacement="story")
  token<-tokens_replace(token,pattern="struggled",replacement="struggle")
  token<-tokens_replace(token,pattern="struggles",replacement="struggle")
  token<-tokens_replace(token,pattern="struggling",replacement="struggle")
  token<-tokens_replace(token,pattern="suffered",replacement="suffer")
  token<-tokens_replace(token,pattern="suffering",replacement="suffer")
  token<-tokens_replace(token,pattern="suicidal",replacement="suicide")
  token<-tokens_replace(token,pattern="supported",replacement="support")
  token<-tokens_replace(token,pattern="supporters",replacement="support")
  token<-tokens_replace(token,pattern="supporting",replacement="support")
  token<-tokens_replace(token,pattern="supportive",replacement="support")
  token<-tokens_replace(token,pattern="supports",replacement="support")
  token<-tokens_replace(token,pattern="supposed",replacement="suppose")
  token<-tokens_replace(token,pattern="surgeries",replacement="surgery")
  token<-tokens_replace(token,pattern="switches",replacement="switch")
  token<-tokens_replace(token,pattern="switching",replacement="switch")
  token<-tokens_replace(token,pattern="symptoms",replacement="symptom")
  
  token<-tokens_replace(token,pattern="takes",replacement="take")
  token<-tokens_replace(token,pattern="taking",replacement="take")
  token<-tokens_replace(token,pattern="took",replacement="take")
  token<-tokens_replace(token,pattern="talked",replacement="talk")
  token<-tokens_replace(token,pattern="taking",replacement="talk")
  token<-tokens_replace(token,pattern="talks",replacement="talk")
  token<-tokens_replace(token,pattern="taller",replacement="tall")
  token<-tokens_replace(token,pattern="tallest",replacement="tall")
  token<-tokens_replace(token,pattern="teen",replacement="teeneger")
  token<-tokens_replace(token,pattern="teenage",replacement="teeneger")
  token<-tokens_replace(token,pattern="teens",replacement="teeneger")
  token<-tokens_replace(token,pattern="telling",replacement="tell")
  token<-tokens_replace(token,pattern="tells",replacement="tell")
  token<-tokens_replace(token,pattern="terms",replacement="term")
  token<-tokens_replace(token,pattern="terrified",replacement="terrible")
  token<-tokens_replace(token,pattern="thank",replacement="thanks")
  token<-tokens_replace(token,pattern="therapist",replacement="therapy")
  token<-tokens_replace(token,pattern="therapists",replacement="therapy")
  token<-tokens_replace(token,pattern="therapies",replacement="therapy")
  token<-tokens_replace(token,pattern="thigh",replacement="thighs")
  token<-tokens_replace(token,pattern="thing",replacement="things")
  token<-tokens_replace(token,pattern="thinking",replacement="think")
  token<-tokens_replace(token,pattern="thinks",replacement="think")
  token<-tokens_replace(token,pattern="times",replacement="time")
  token<-tokens_replace(token,pattern="tops",replacement="top")
  token<-tokens_replace(token,pattern="toys",replacement="toy")
  token<-tokens_replace(token,pattern="tomboyish",replacement="tomboy")
  token<-tokens_replace(token,pattern="traditionally",replacement="traditional")
  token<-tokens_replace(token,pattern="transgenders",replacement="transgender")
  token<-tokens_replace(token,pattern="transphobic",replacement="transphobia")
  token<-tokens_replace(token,pattern="transitioned",replacement="transition")
  token<-tokens_replace(token,pattern="treatments",replacement="treatment")
  token<-tokens_replace(token,pattern="treated",replacement="treatment")
  token<-tokens_replace(token,pattern="treat",replacement="treatment")
  token<-tokens_replace(token,pattern="treating",replacement="treatment")
  token<-tokens_replace(token,pattern="tried",replacement="try")
  token<-tokens_replace(token,pattern="trying",replacement="try")
  token<-tokens_replace(token,pattern="turned",replacement="turn")
  token<-tokens_replace(token,pattern="turns",replacement="turn")
  token<-tokens_replace(token,pattern="triggered",replacement="trigger")
  token<-tokens_replace(token,pattern="triggering",replacement="trigger")
  token<-tokens_replace(token,pattern="triggers",replacement="trigger")
  
  token<-tokens_replace(token,pattern="used",replacement="use")
  token<-tokens_replace(token,pattern="using",replacement="use")
  
  token<-tokens_replace(token,pattern="venting",replacement="vent")
  token<-tokens_replace(token,pattern="viewed",replacement="view")
  token<-tokens_replace(token,pattern="viewing",replacement="view")
  token<-tokens_replace(token,pattern="views",replacement="view")
  token<-tokens_replace(token,pattern="voices",replacement="voice")
  
  token<-tokens_replace(token,pattern="waiting",replacement="wait")
  token<-tokens_replace(token,pattern="wakes",replacement="wake")
  token<-tokens_replace(token,pattern="waking",replacement="wake")
  token<-tokens_replace(token,pattern="walked",replacement="walk")
  token<-tokens_replace(token,pattern="walking",replacement="walk")
  token<-tokens_replace(token,pattern="wanted",replacement="want")
  token<-tokens_replace(token,pattern="walked",replacement="walk")
  token<-tokens_replace(token,pattern="wants",replacement="walk")
  token<-tokens_replace(token,pattern="watching",replacement="watch")
  token<-tokens_replace(token,pattern="wearing",replacement="wear")
  token<-tokens_replace(token,pattern="weeks",replacement="week")
  token<-tokens_replace(token,pattern="willing",replacement="will")
  token<-tokens_replace(token,pattern="wished",replacement="wish")
  token<-tokens_replace(token,pattern="wishes",replacement="wish")
  token<-tokens_replace(token,pattern="wishing",replacement="wish")
  token<-tokens_replace(token,pattern="women",replacement="woman")
  token<-tokens_replace(token,pattern="womens",replacement="woman")
  token<-tokens_replace(token,pattern="words",replacement="word")
  token<-tokens_replace(token,pattern="wore",replacement="wear")
  token<-tokens_replace(token,pattern="worked",replacement="work")
  token<-tokens_replace(token,pattern="working",replacement="work")
  token<-tokens_replace(token,pattern="works",replacement="work")
  token<-tokens_replace(token,pattern="worst",replacement="worse")
  token<-tokens_replace(token,pattern="written",replacement="write")
  token<-tokens_replace(token,pattern="years",replacement="year")
  token<-tokens_replace(token,pattern="young",replacement="youth")
  token<-tokens_replace(token,pattern="younger",replacement="youth")
  
  token<-tokens_replace(token,pattern="questions",replacement="question")
  
  token<-tokens_replace(token,pattern="referred",replacement="refer")
  
  token<-tokens_replace(token,pattern="says",replacement="say")
  token<-tokens_replace(token,pattern="stressed",replacement="stress")
  
  token<-tokens_replace(token,pattern="taken",replacement="take")
  token<-tokens_replace(token,pattern="transitioning",replacement="transition")
  token<-tokens_replace(token,pattern="told",replacement="tell")
  
  token<-tokens_replace(token,pattern="understanding",replacement="understand")
  token<-tokens_replace(token,pattern="uncomfortable",replacement="discomfort")
  
  token<-tokens_replace(token,pattern="videos",replacement="video")
  
  token<-tokens_replace(token,pattern="wanna",replacement="want")
  token<-tokens_replace(token,pattern="wondering",replacement="wonder")
  token<-tokens_replace(token,pattern="ways",replacement="way")
  token<-tokens_replace(token,pattern="worried",replacement="worry")
}
